# Generated by Django 6.0.3 on 2026-03-11 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_number', models.CharField(max_length=10, unique=True, verbose_name='Número da Vaga')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Ocupada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
            ],
            options={
                'verbose_name': 'Vaga de Estacionamento',
                'verbose_name_plural': 'Vagas de Estacionamento',
            },
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(verbose_name='Hora de Entrada')),
                ('exit_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_records', to='vehicles.vehicle', verbose_name='Veículo')),
                ('parking_spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_records', to='parking.parkingspot', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Registro de Estacionamento',
                'verbose_name_plural': 'Registros de Estacionamento',
            },
        ),
    ]
