services:

  parking_service:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - parking_db
    env_file:
      - .env
    volumes:
      - .:/estacionamento_django 

  parking_db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
volumes:
  postgres_data:


