# Generated by Django 6.0.3 on 2026-03-13 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Modelo')),
            ],
            options={
                'verbose_name': 'Modelo do Veículo',
                'verbose_name_plural': 'Modelos dos Veículos',
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.model', verbose_name='Modelo'),
        ),
    ]
